name = "slsqp"
version = "1.6.0"
license = "BSD-3-Clause"
author = "Jacob Williams"
maintainer = "https://github.com/jacobwilliams"
copyright = "Copyright (c) 2016-2025, Jacob Williams"
description = "Modern Fortran Edition of the SLSQP Optimizer"
homepage = "https://github.com/jacobwilliams/slsqp"
keywords = ["optimization"]

[library]
source-dir = "src"

[install]
library = true

[build]
auto-executables = false
auto-examples = false
auto-tests = true