daxpy – slsqp
daxpy Subroutine
38 statements
Source File
public pure subroutine daxpy(n, da, dx, incx, dy, incy)
constant times a vector plus a vector. uses unrolled loops for increments equal to one.
Author
jack dongarra, linpack, 3/11/78.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(in) :: da
real(kind=wp), intent(in), dimension(*) :: dx
integer, intent(in) :: incx
real(kind=wp), intent(inout), dimension(*) :: dy
integer, intent(in) :: incy
Called by
Contents
Source Code
daxpy
Source Code
    pure subroutine daxpy(n,da,dx,incx,dy,incy)
    implicit none
    integer,intent(in)                  :: n
    real(wp),intent(in)                 :: da
    real(wp),dimension(*),intent(in)    :: dx
    integer,intent(in)                  :: incx
    real(wp),dimension(*),intent(inout) :: dy
    integer,intent(in)                  :: incy
    integer :: i , ix , iy , m , mp1
    if ( n<=0 ) return
    if ( abs(da)<=zero ) return
    if ( incx==1 .and. incy==1 ) then
        ! code for both increments equal to 1
        ! clean-up loop
        m = mod(n,4)
        if ( m/=0 ) then
            do i = 1 , m
                dy(i) = dy(i) + da*dx(i)
            end do
            if ( n<4 ) return
        end if
        mp1 = m + 1
        do i = mp1 , n , 4
            dy(i) = dy(i) + da*dx(i)
            dy(i+1) = dy(i+1) + da*dx(i+1)
            dy(i+2) = dy(i+2) + da*dx(i+2)
            dy(i+3) = dy(i+3) + da*dx(i+3)
        end do
    else
        ! code for unequal increments or equal increments
        ! not equal to 1
        ix = 1
        iy = 1
        if ( incx<0 ) ix = (-n+1)*incx + 1
        if ( incy<0 ) iy = (-n+1)*incy + 1
        do i = 1 , n
            dy(iy) = dy(iy) + da*dx(ix)
            ix = ix + incx
            iy = iy + incy
        end do
    end if
    end subroutine daxpy
Call graph
slsqpb calls daxpy, lsq
ldp calls daxpy
lsi calls daxpy, ldp
slsqp calls slsqpb
lsei calls lsi
slsqp_wrapper calls slsqp
lsq calls lsei