dcopy – slsqp
dcopy Subroutine
39 statements
Source File
public pure subroutine dcopy(n, dx, incx, dy, incy)
copies a vector, x, to a vector, y. uses unrolled loops for increments equal to one.
Author
jack dongarra, linpack, 3/11/78.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(in), dimension(*) :: dx
integer, intent(in) :: incx
real(kind=wp), intent(out), dimension(*) :: dy
integer, intent(in) :: incy
Called by
Contents
Source Code
dcopy
Source Code
    pure subroutine dcopy(n,dx,incx,dy,incy)
    implicit none
    integer,intent(in)                :: n
    real(wp),dimension(*),intent(in)  :: dx
    integer,intent(in)                :: incx
    real(wp),dimension(*),intent(out) :: dy
    integer,intent(in)                :: incy
    integer :: i , ix , iy , m , mp1
    if ( n<=0 ) return
    if ( incx==1 .and. incy==1 ) then
        ! code for both increments equal to 1
        ! clean-up loop
        m = mod(n,7)
        if ( m/=0 ) then
            do i = 1 , m
                dy(i) = dx(i)
            end do
            if ( n<7 ) return
        end if
        mp1 = m + 1
        do i = mp1 , n , 7
            dy(i) = dx(i)
            dy(i+1) = dx(i+1)
            dy(i+2) = dx(i+2)
            dy(i+3) = dx(i+3)
            dy(i+4) = dx(i+4)
            dy(i+5) = dx(i+5)
            dy(i+6) = dx(i+6)
        end do
    else
        ! code for unequal increments or equal increments
        ! not equal to 1
        ix = 1
        iy = 1
        if ( incx<0 ) ix = (-n+1)*incx + 1
        if ( incy<0 ) iy = (-n+1)*incy + 1
        do i = 1 , n
            dy(iy) = dx(ix)
            ix = ix + incx
            iy = iy + incy
        end do
    end if
    end subroutine dcopy
Call graph
slsqpb calls dcopy, lsq
ldp calls dcopy
lsei calls dcopy, lsi
lsq calls dcopy, lsei
slsqp calls slsqpb
lsi calls ldp
slsqp_wrapper calls slsqp