diff – slsqp
diff Function
7 statements
Source File
private pure elemental function diff(u, v) result(d)
Replaced statement function in the original code. Returns .
Arguments
Type Intent Optional Attributes Name
real(kind=wp), intent(in) :: u
real(kind=wp), intent(in) :: v
Return Value real(kind=wp)
Called by
Contents
Source Code
diff
Source Code
    pure elemental function diff(u,v) result(d)
    implicit none
    real(wp),intent(in) :: u
    real(wp),intent(in) :: v
    real(wp)            :: d
    d = u - v
    end function diff
Call graph
hfti calls diff
ldp calls diff, nnls
nnls calls diff
lsei calls hfti, lsi
lsi calls ldp
lsq calls lsei
slsqpb calls lsq
slsqp calls slsqpb
slsqp_wrapper calls slsqp