dnrm2 – slsqp
dnrm2 Function
29 statements
Source File
public pure function dnrm2(n, x, incx) result(norm)
Function that returns the Euclidean norm of a vector .
Further details
this version written on 25-october-1982.
modified on 14-october-1993 to inline the call to dlassq. sven hammarling, nag ltd.
Converted to modern Fortran, Jacob Williams, Jan. 2016.
Note
Replaced original SLSQP routine with this one from BLAS.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
real(kind=wp), intent(in), dimension(*) :: x
integer, intent(in) :: incx
Return Value real(kind=wp)
Called by
Contents
Source Code
dnrm2
Source Code
    pure function dnrm2(n,x,incx) result(norm)
    implicit none
    integer,intent(in)               :: incx
    integer,intent(in)               :: n
    real(wp),dimension(*),intent(in) :: x
    real(wp)                         :: norm
    real(wp) :: absxi , scale , ssq
    integer :: ix
    if ( n<1 .or. incx<1 ) then
        norm = zero
    elseif ( n==1 ) then
        norm = abs(x(1))
    else
        scale = zero
        ssq = one
        ! the following loop is equivalent to this call to the lapack
        ! auxiliary routine:
        ! call dlassq( n, x, incx, scale, ssq )
        do ix = 1 , 1 + (n-1)*incx , incx
            if ( abs(x(ix))>zero ) then
                absxi = abs(x(ix))
                if ( scale<absxi ) then
                    ssq = one + ssq*(scale/absxi)**2
                    scale = absxi
                else
                    ssq = ssq + (absxi/scale)**2
                end if
            end if
        end do
        norm = scale*sqrt(ssq)
    end if
    end function dnrm2
Call graph
check_convergence calls dnrm2
ldp calls dnrm2
lsei calls dnrm2, lsi
lsi calls dnrm2, ldp
lsq calls lsei
slsqpb calls lsq
slsqp calls slsqpb
slsqp_wrapper calls slsqp